version: '3.8'

services:
  devflow-mysql:
    image: mysql:8.0
    container_name: devflow_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devflow_root_secret
      MYSQL_DATABASE: devflow_db
      MYSQL_USER: devflow_user
      MYSQL_PASSWORD: devflow_senha123
    ports:
      - "3306:3306"
    volumes:
      - devflow_mysqldata:/var/lib/mysql

volumes:
  devflow_mysqldata: